name: Release

on:
  workflow_dispatch:
    branches: ["master"]
    inputs:
      dry-run:
        description: Set `true` if you do not release it yet
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm run release:dry-run
        if: ${{ github.event.inputs.dry-run == 'true' }}
      - run: npm run release
        if: ${{ github.event.inputs.dry-run == '' }}
      - run: echo "::set-output name=head-sha::$(git rev-parse HEAD)"
        if: ${{ github.event.inputs.dry-run == '' }}
        id: set-head-sha
      - uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.dry-run == '' }}
        with:
          body: |
            See the [changelog](https://github.com/${{ github.repository }}/blob/${{ steps.set-head-sha.outputs.head-sha }}/CHANGELOG.md) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
